trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'
- script: npm install --save-dev
  displayName: 'npm install'
- script: npm run test
  displayName: 'run tests'
